name: vuejs_docs_alfred_workflow
description: Search the Vue.js documentation using Alfred

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 2.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  alfred_workflow: ^0.2.10
  algolia: ^1.1.1
  args: ^2.3.0
  cli_script: ^0.2.6
  collection: ^1.16.0
  html_unescape: ^2.0.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.1.7
  dart_code_metrics: ^5.0.1
  json_serializable: ^6.1.5
  lints: ^2.0.0
